version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: store_bot
    ports: 
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  django:
    build: 
      context: ./admin
      args:
        progress: plain
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  
  bot:
    build: 
      context: ./bot
      args:
        progress: plain
    depends_on:
      - db
      - redis
      - django