# Generated by Django 5.0.4 on 2024-04-09 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='photo_id',
        ),
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(default=1, upload_to='content/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
