# Generated by Django 5.0.4 on 2024-04-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.ImageField(upload_to='content/')),
                ('tg_id', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Постер',
                'verbose_name_plural': 'Постеры',
                'db_table': 'posters',
            },
        ),
    ]
