# Generated by Django 5.0.4 on 2024-04-10 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_poster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='photo',
        ),
    ]
