# Generated by Django 5.0.4 on 2024-04-10 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_product_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='poster',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='main.poster'),
        ),
    ]
