# Generated by Django 5.0.4 on 2024-04-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_product_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poster',
            name='tg_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
