# Generated by Django 5.0.4 on 2024-04-10 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_poster_tg_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_user_id', models.BigIntegerField()),
                ('product_id', models.BigIntegerField()),
                ('count', models.IntegerField()),
            ],
        ),
    ]
