# Generated by Django 5.0.4 on 2024-04-10 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_basket'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='basket',
            table='basket',
        ),
    ]
