# Generated by Django 5.0.4 on 2024-04-11 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_basket_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='tg_user_id',
            new_name='user_id',
        ),
    ]
