# Generated by Django 5.0.4 on 2024-04-11 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_rename_tg_user_id_basket_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='product_id',
        ),
        migrations.AddField(
            model_name='basket',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.product'),
            preserve_default=False,
        ),
    ]
