# Generated by Django 5.0.4 on 2024-04-12 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0015_product_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="poster",
            name="file",
            field=models.BinaryField(null=True),
        ),
    ]
