# Generated by Django 5.0.4 on 2024-04-12 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0016_poster_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poster",
            name="file",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
