# Generated by Django 5.0.4 on 2024-04-12 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0018_alter_poster_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poster",
            name="path",
            field=models.ImageField(null=True, upload_to="content/"),
        ),
    ]
