# Generated by Django 5.0.4 on 2024-04-12 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0019_alter_poster_path"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="poster",
            name="file",
        ),
    ]
